version: '3'
services:
  caddy:
    image: caddy:2.3.0-rc.1-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
    - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    - ./caddy/sites:/srv
    - ./caddy/config:/config
    - ./caddy/data:/data
  hugo:
    image: jojomi/hugo:0.76
    volumes:
      - ./hugo:/src
      - ./caddy/sites/hugo:/output
    environment:
      - HUGO_ENV=production
      - HUGO_REFRESH_TIME=300
      - HUGO_THEME=hugo-PaperMod
      - HUGO_BASEURL=https://akmnn.de/
    restart: always
  minecraft:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      MAX_MEMORY: 2G
    volumes:
      - ./mcdata:/data
