version: '3'
services:
  caddy:
    image: abiosoft/caddy:latest
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
    - ./caddy/Caddyfile:/etc/Caddyfile
    - ./caddy/certificates:/root/.caddy
    - ./caddy/sites:/www/
  youtrack:
    image: jetbrains/youtrack:2019.3.64090
    ports:
      - '8080'
    volumes:
      - ./youtrack/data:/opt/youtrack/data
      - ./youtrack/conf:/opt/youtrack/conf
      - ./youtrack/logs:/opt/youtrack/logs
      - ./youtrack/backups:/opt/youtrack/backups
  minecraft:
    image: itzg/minecraft-server
    ports:
      - '25565:25565'
    volumes:
      - ./mc:/data
    environment:
      EULA: 'TRUE'
      CONSOLE: 'true'
      ENABLE_RCON: 'true'
      RCON_PASSWORD: ''
      RCON_PORT: 28016
    restart: always
