version: '3'
services:
  caddy:
    image: caddy:2.1.1-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
    - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    - ./caddy/sites:/srv
    - ./caddy/config:/config
    - ./caddy/data:/data
  hugo:
    image: jojomi/hugo:latest
    volumes:
      - ./hugo:/src
      - ./caddy/sites/hugo:/output
    environment:
      - HUGO_REFRESH_TIME=300
      - HUGO_THEME=hugo-PaperMod
      - HUGO_BASEURL=https://akmnn.de/
    restart: always
